name: Java CI with Maven

on:
  push:
    branches: [ "Dev" ]
  pull_request:
    branches: [ "Dev" ]
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch name'
        required: true
        default: 'Dev'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run:  mvn -B package -DskipTests --file pom.xml
    
    - name: Upload JAR as artifact
      uses: actions/upload-artifact@v3.1.3
      with:
        name: Spotify-Back
        path: target/*.jar

  push:
    needs: build
    if: ${{ needs.build.result == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v2
        with:
           ref: ${{ github.event.inputs.branch }}
           fetch-depth: 0
      - name: Revert pushed commit
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git revert --no-edit HEAD
          git push

        
